### ISSUE TITLE
Access denied. Somehow.

### ISSUE THREAD

**Issue by kuronekony4n** [diciaup/assistant-cli#3]
**Describe the bug**
Access denied. I already logged in and this the response.

**AssistantCli Version**
1.1.2

**Screenshots**
![Screenshot_521](https://user-images.githubusercontent.com/38156932/210044530-13f3308b-d091-4eed-9b0f-99a96a1598a0.png)

**Comment by muhiris** [comment]
I am also having the same issue. 
![image](https://user-images.githubusercontent.com/80543033/210215855-e90a1909-40ca-46ca-867d-206a2ddcdf90.png)

**Comment by diciaup** [comment]
Hello guys, i am working on this bug in branch feature/cloudflare-response-handler, this is caused by the integration with cloudflare, i don't know why but the other apis works fine, so the authentication process works properly, only the /conversation api returns access denied, so i thinks that some cookies are missing

**Comment by diciaup** [comment]
The issue is solved on version 1.3.2
